theme: jekyll-theme-tactile
title: Stargazing
description: Stargazing by Amanda Leiserowitz, an interactive constellation-drawing program; the user is given a random sky to connect stars. Every 10 seconds, the sky and drawings are reset 
